version: '3.8'

services:
  database:
    container_name: ms-game-database
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: ms-game
    ports:
      - "5415:5432"
    expose:
      - 5432
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "ms-game" ]
      interval: 3s
      timeout: 10s
      retries: 2
  ms-game:
    container_name: ms-game-api
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROFILE: $PROFILE
        PORT: $PORT
    env_file:
      - .env
    image: ms-game-image
    expose:
      - $PORT
    ports:
      - "8085:$PORT"
    networks:
      - internal-network
    depends_on:
      database:
        condition: service_healthy
volumes:
  database-volume:
    name: ms-game-database-volume
networks:
  internal-network:
    name: ms-game-network