version: '3.8'

services:
  ms-movie-native:
    container_name: ms-movie-api-native
    image: ms-movie-native-image
    env_file:
      - .env
    expose:
      - $PORT
    ports:
      - "8086:$PORT"
    networks:
      - internal-network
volumes:
  database-volume:
    name: ms-movie-database-volume
networks:
  internal-network:
    name: ms-movie-network