version: '3.8'

services:
  database:
    container_name: ms-movie-database
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ms-movie
    ports:
      - "5415:5432"
    expose:
      - 5432
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - internal-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-d", "param_api" ]
#      interval: 5s
#      timeout: 10s
#      retries: 2

volumes:
  database-volume:
    name: ms-movie-database-volume
networks:
  internal-network:
    name: ms-movie-network