spring:
  application:
    name: ms-movie
  profiles:
    active: ${PROFILE:local}
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      max-lifetime: 1800000
      maximum-pool-size: ${MAX_DB_POOL_SIZE:50}
      validation-timeout: 2000
      leak-detection-threshold: 20000
  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false

server:
  servlet:
    contextPath: /ms-movie
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8080}

management:
  health:
    defaults:
      enabled: false
    db:
      enabled: true
  endpoint:
    health:
        show-details: "always"
        enabled: true
  endpoints:
    enabled-by-default: false

springdoc:
  show-actuator: true
  swagger-ui:
    path: /docs
    operationsSorter: method